### ISSUE TITLE
Assuming too much on the local folder

### ISSUE THREAD

**Issue by fengye** [Zerbera2/Getting_Clean_Data#1]
Hi,
I happened to be the reviewer of your work on Coursera. I found your script are assuming too much on the local folder position, e.g. you're trying to setwd to "C:/Users/Helen/Desktop/Getting_Clean_Data" and can result an error on my PC/Mac.

Also, please remind in the end you didn't output an text file that contains the tidy data. Instead a nice table view is displayed. I don't think it meets the requirements of the course project. 

If you have time to modify the script, I'd be happy to rate you a full score. However you probably should do it before this weekend otherwise the peer review will be closed.

**Comment by Zerbera2** [comment]
Hi Ye Feng,

Thank you for this. I think I understand what you mean with the local
folder position, although I don't really know how to generalise a script
for any user. I'll try somehow.

Also, I outputted the text file separately, because I didn't read this as
part of the instructions to be included in the script. But I'll change that
too.

I'll do that later today. Thanks for bringing it to my attention.

Regards,
Helen

Helen J. Addison
Tel. +44 (0)7795 990 153
addison.hj@gmail.com

**Comment by AddisonHJ** [comment]
Hi Ye Feng,
I've made changes now to the script to generalise the local folder position and to write the dataframe to a text file. I had earlier written a separate script to write the object to a text file in order to upload the text file to the Coursera course site. I didn't realise it ought to be in the main script too.
Many thanks for advising me on this!
Helen

**Comment by fengye** [comment]
Hi Helen,
I've managed to run the code as I created a "Desktop" folder along with where I put your code :) It runs smoothly
